function kalias -d 'Load Kubernetes abbreviations'
    abbr --add --global k 'kubectl'
    abbr --add --global ksys 'kubectl --namespace=kube-system'
    abbr --add --global ka 'kubectl apply --recursive -f'
    abbr --add --global ksysa 'kubectl --namespace=kube-system apply --recursive -f'
    abbr --add --global kak 'kubectl apply -k'
    abbr --add --global kk 'kubectl kustomize'
    abbr --add --global kex 'kubectl exec -i -t'
    abbr --add --global ksysex 'kubectl --namespace=kube-system exec -i -t'
    abbr --add --global klo 'kubectl logs -f'
    abbr --add --global ksyslo 'kubectl --namespace=kube-system logs -f'
    abbr --add --global klop 'kubectl logs -f -p'
    abbr --add --global ksyslop 'kubectl --namespace=kube-system logs -f -p'
    abbr --add --global kp 'kubectl proxy'
    abbr --add --global kpf 'kubectl port-forward'
    abbr --add --global kg 'kubectl get'
    abbr --add --global ksysg 'kubectl --namespace=kube-system get'
    abbr --add --global kd 'kubectl describe'
    abbr --add --global ksysd 'kubectl --namespace=kube-system describe'
    abbr --add --global krm 'kubectl delete'
    abbr --add --global ksysrm 'kubectl --namespace=kube-system delete'
    abbr --add --global krun 'kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
    abbr --add --global ksysrun 'kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
    abbr --add --global kgpo 'kubectl get pods'
    abbr --add --global ksysgpo 'kubectl --namespace=kube-system get pods'
    abbr --add --global kdpo 'kubectl describe pods'
    abbr --add --global ksysdpo 'kubectl --namespace=kube-system describe pods'
    abbr --add --global krmpo 'kubectl delete pods'
    abbr --add --global ksysrmpo 'kubectl --namespace=kube-system delete pods'
    abbr --add --global kgdep 'kubectl get deployment'
    abbr --add --global ksysgdep 'kubectl --namespace=kube-system get deployment'
    abbr --add --global kddep 'kubectl describe deployment'
    abbr --add --global ksysddep 'kubectl --namespace=kube-system describe deployment'
    abbr --add --global krmdep 'kubectl delete deployment'
    abbr --add --global ksysrmdep 'kubectl --namespace=kube-system delete deployment'
    abbr --add --global kgsvc 'kubectl get service'
    abbr --add --global ksysgsvc 'kubectl --namespace=kube-system get service'
    abbr --add --global kdsvc 'kubectl describe service'
    abbr --add --global ksysdsvc 'kubectl --namespace=kube-system describe service'
    abbr --add --global krmsvc 'kubectl delete service'
    abbr --add --global ksysrmsvc 'kubectl --namespace=kube-system delete service'
    abbr --add --global kging 'kubectl get ingress'
    abbr --add --global ksysging 'kubectl --namespace=kube-system get ingress'
    abbr --add --global kding 'kubectl describe ingress'
    abbr --add --global ksysding 'kubectl --namespace=kube-system describe ingress'
    abbr --add --global krming 'kubectl delete ingress'
    abbr --add --global ksysrming 'kubectl --namespace=kube-system delete ingress'
    abbr --add --global kgcm 'kubectl get configmap'
    abbr --add --global ksysgcm 'kubectl --namespace=kube-system get configmap'
    abbr --add --global kdcm 'kubectl describe configmap'
    abbr --add --global ksysdcm 'kubectl --namespace=kube-system describe configmap'
    abbr --add --global krmcm 'kubectl delete configmap'
    abbr --add --global ksysrmcm 'kubectl --namespace=kube-system delete configmap'
    abbr --add --global kgsec 'kubectl get secret'
    abbr --add --global ksysgsec 'kubectl --namespace=kube-system get secret'
    abbr --add --global kdsec 'kubectl describe secret'
    abbr --add --global ksysdsec 'kubectl --namespace=kube-system describe secret'
    abbr --add --global krmsec 'kubectl delete secret'
    abbr --add --global ksysrmsec 'kubectl --namespace=kube-system delete secret'
    abbr --add --global kgno 'kubectl get nodes'
    abbr --add --global kdno 'kubectl describe nodes'
    abbr --add --global kgns 'kubectl get namespaces'
    abbr --add --global kdns 'kubectl describe namespaces'
    abbr --add --global krmns 'kubectl delete namespaces'
    abbr --add --global kgoyaml 'kubectl get -o=yaml'
    abbr --add --global ksysgoyaml 'kubectl --namespace=kube-system get -o=yaml'
    abbr --add --global kgpooyaml 'kubectl get pods -o=yaml'
    abbr --add --global ksysgpooyaml 'kubectl --namespace=kube-system get pods -o=yaml'
    abbr --add --global kgdepoyaml 'kubectl get deployment -o=yaml'
    abbr --add --global ksysgdepoyaml 'kubectl --namespace=kube-system get deployment -o=yaml'
    abbr --add --global kgsvcoyaml 'kubectl get service -o=yaml'
    abbr --add --global ksysgsvcoyaml 'kubectl --namespace=kube-system get service -o=yaml'
    abbr --add --global kgingoyaml 'kubectl get ingress -o=yaml'
    abbr --add --global ksysgingoyaml 'kubectl --namespace=kube-system get ingress -o=yaml'
    abbr --add --global kgcmoyaml 'kubectl get configmap -o=yaml'
    abbr --add --global ksysgcmoyaml 'kubectl --namespace=kube-system get configmap -o=yaml'
    abbr --add --global kgsecoyaml 'kubectl get secret -o=yaml'
    abbr --add --global ksysgsecoyaml 'kubectl --namespace=kube-system get secret -o=yaml'
    abbr --add --global kgnooyaml 'kubectl get nodes -o=yaml'
    abbr --add --global kgnsoyaml 'kubectl get namespaces -o=yaml'
    abbr --add --global kgowide 'kubectl get -o=wide'
    abbr --add --global ksysgowide 'kubectl --namespace=kube-system get -o=wide'
    abbr --add --global kgpoowide 'kubectl get pods -o=wide'
    abbr --add --global ksysgpoowide 'kubectl --namespace=kube-system get pods -o=wide'
    abbr --add --global kgdepowide 'kubectl get deployment -o=wide'
    abbr --add --global ksysgdepowide 'kubectl --namespace=kube-system get deployment -o=wide'
    abbr --add --global kgsvcowide 'kubectl get service -o=wide'
    abbr --add --global ksysgsvcowide 'kubectl --namespace=kube-system get service -o=wide'
    abbr --add --global kgingowide 'kubectl get ingress -o=wide'
    abbr --add --global ksysgingowide 'kubectl --namespace=kube-system get ingress -o=wide'
    abbr --add --global kgcmowide 'kubectl get configmap -o=wide'
    abbr --add --global ksysgcmowide 'kubectl --namespace=kube-system get configmap -o=wide'
    abbr --add --global kgsecowide 'kubectl get secret -o=wide'
    abbr --add --global ksysgsecowide 'kubectl --namespace=kube-system get secret -o=wide'
    abbr --add --global kgnoowide 'kubectl get nodes -o=wide'
    abbr --add --global kgnsowide 'kubectl get namespaces -o=wide'
    abbr --add --global kgojson 'kubectl get -o=json'
    abbr --add --global ksysgojson 'kubectl --namespace=kube-system get -o=json'
    abbr --add --global kgpoojson 'kubectl get pods -o=json'
    abbr --add --global ksysgpoojson 'kubectl --namespace=kube-system get pods -o=json'
    abbr --add --global kgdepojson 'kubectl get deployment -o=json'
    abbr --add --global ksysgdepojson 'kubectl --namespace=kube-system get deployment -o=json'
    abbr --add --global kgsvcojson 'kubectl get service -o=json'
    abbr --add --global ksysgsvcojson 'kubectl --namespace=kube-system get service -o=json'
    abbr --add --global kgingojson 'kubectl get ingress -o=json'
    abbr --add --global ksysgingojson 'kubectl --namespace=kube-system get ingress -o=json'
    abbr --add --global kgcmojson 'kubectl get configmap -o=json'
    abbr --add --global ksysgcmojson 'kubectl --namespace=kube-system get configmap -o=json'
    abbr --add --global kgsecojson 'kubectl get secret -o=json'
    abbr --add --global ksysgsecojson 'kubectl --namespace=kube-system get secret -o=json'
    abbr --add --global kgnoojson 'kubectl get nodes -o=json'
    abbr --add --global kgnsojson 'kubectl get namespaces -o=json'
    abbr --add --global kgall 'kubectl get --all-namespaces'
    abbr --add --global kdall 'kubectl describe --all-namespaces'
    abbr --add --global kgpoall 'kubectl get pods --all-namespaces'
    abbr --add --global kdpoall 'kubectl describe pods --all-namespaces'
    abbr --add --global kgdepall 'kubectl get deployment --all-namespaces'
    abbr --add --global kddepall 'kubectl describe deployment --all-namespaces'
    abbr --add --global kgsvcall 'kubectl get service --all-namespaces'
    abbr --add --global kdsvcall 'kubectl describe service --all-namespaces'
    abbr --add --global kgingall 'kubectl get ingress --all-namespaces'
    abbr --add --global kdingall 'kubectl describe ingress --all-namespaces'
    abbr --add --global kgcmall 'kubectl get configmap --all-namespaces'
    abbr --add --global kdcmall 'kubectl describe configmap --all-namespaces'
    abbr --add --global kgsecall 'kubectl get secret --all-namespaces'
    abbr --add --global kdsecall 'kubectl describe secret --all-namespaces'
    abbr --add --global kgnsall 'kubectl get namespaces --all-namespaces'
    abbr --add --global kdnsall 'kubectl describe namespaces --all-namespaces'
    abbr --add --global kgsl 'kubectl get --show-labels'
    abbr --add --global ksysgsl 'kubectl --namespace=kube-system get --show-labels'
    abbr --add --global kgposl 'kubectl get pods --show-labels'
    abbr --add --global ksysgposl 'kubectl --namespace=kube-system get pods --show-labels'
    abbr --add --global kgdepsl 'kubectl get deployment --show-labels'
    abbr --add --global ksysgdepsl 'kubectl --namespace=kube-system get deployment --show-labels'
    abbr --add --global krmall 'kubectl delete --all'
    abbr --add --global ksysrmall 'kubectl --namespace=kube-system delete --all'
    abbr --add --global krmpoall 'kubectl delete pods --all'
    abbr --add --global ksysrmpoall 'kubectl --namespace=kube-system delete pods --all'
    abbr --add --global krmdepall 'kubectl delete deployment --all'
    abbr --add --global ksysrmdepall 'kubectl --namespace=kube-system delete deployment --all'
    abbr --add --global krmsvcall 'kubectl delete service --all'
    abbr --add --global ksysrmsvcall 'kubectl --namespace=kube-system delete service --all'
    abbr --add --global krmingall 'kubectl delete ingress --all'
    abbr --add --global ksysrmingall 'kubectl --namespace=kube-system delete ingress --all'
    abbr --add --global krmcmall 'kubectl delete configmap --all'
    abbr --add --global ksysrmcmall 'kubectl --namespace=kube-system delete configmap --all'
    abbr --add --global krmsecall 'kubectl delete secret --all'
    abbr --add --global ksysrmsecall 'kubectl --namespace=kube-system delete secret --all'
    abbr --add --global krmnsall 'kubectl delete namespaces --all'
    abbr --add --global kgw 'kubectl get --watch'
    abbr --add --global ksysgw 'kubectl --namespace=kube-system get --watch'
    abbr --add --global kgpow 'kubectl get pods --watch'
    abbr --add --global ksysgpow 'kubectl --namespace=kube-system get pods --watch'
    abbr --add --global kgdepw 'kubectl get deployment --watch'
    abbr --add --global ksysgdepw 'kubectl --namespace=kube-system get deployment --watch'
    abbr --add --global kgsvcw 'kubectl get service --watch'
    abbr --add --global ksysgsvcw 'kubectl --namespace=kube-system get service --watch'
    abbr --add --global kgingw 'kubectl get ingress --watch'
    abbr --add --global ksysgingw 'kubectl --namespace=kube-system get ingress --watch'
    abbr --add --global kgcmw 'kubectl get configmap --watch'
    abbr --add --global ksysgcmw 'kubectl --namespace=kube-system get configmap --watch'
    abbr --add --global kgsecw 'kubectl get secret --watch'
    abbr --add --global ksysgsecw 'kubectl --namespace=kube-system get secret --watch'
    abbr --add --global kgnow 'kubectl get nodes --watch'
    abbr --add --global kgnsw 'kubectl get namespaces --watch'
    abbr --add --global kgoyamlall 'kubectl get -o=yaml --all-namespaces'
    abbr --add --global kgpooyamlall 'kubectl get pods -o=yaml --all-namespaces'
    abbr --add --global kgdepoyamlall 'kubectl get deployment -o=yaml --all-namespaces'
    abbr --add --global kgsvcoyamlall 'kubectl get service -o=yaml --all-namespaces'
    abbr --add --global kgingoyamlall 'kubectl get ingress -o=yaml --all-namespaces'
    abbr --add --global kgcmoyamlall 'kubectl get configmap -o=yaml --all-namespaces'
    abbr --add --global kgsecoyamlall 'kubectl get secret -o=yaml --all-namespaces'
    abbr --add --global kgnsoyamlall 'kubectl get namespaces -o=yaml --all-namespaces'
    abbr --add --global kgalloyaml 'kubectl get --all-namespaces -o=yaml'
    abbr --add --global kgpoalloyaml 'kubectl get pods --all-namespaces -o=yaml'
    abbr --add --global kgdepalloyaml 'kubectl get deployment --all-namespaces -o=yaml'
    abbr --add --global kgsvcalloyaml 'kubectl get service --all-namespaces -o=yaml'
    abbr --add --global kgingalloyaml 'kubectl get ingress --all-namespaces -o=yaml'
    abbr --add --global kgcmalloyaml 'kubectl get configmap --all-namespaces -o=yaml'
    abbr --add --global kgsecalloyaml 'kubectl get secret --all-namespaces -o=yaml'
    abbr --add --global kgnsalloyaml 'kubectl get namespaces --all-namespaces -o=yaml'
    abbr --add --global kgwoyaml 'kubectl get --watch -o=yaml'
    abbr --add --global ksysgwoyaml 'kubectl --namespace=kube-system get --watch -o=yaml'
    abbr --add --global kgpowoyaml 'kubectl get pods --watch -o=yaml'
    abbr --add --global ksysgpowoyaml 'kubectl --namespace=kube-system get pods --watch -o=yaml'
    abbr --add --global kgdepwoyaml 'kubectl get deployment --watch -o=yaml'
    abbr --add --global ksysgdepwoyaml 'kubectl --namespace=kube-system get deployment --watch -o=yaml'
    abbr --add --global kgsvcwoyaml 'kubectl get service --watch -o=yaml'
    abbr --add --global ksysgsvcwoyaml 'kubectl --namespace=kube-system get service --watch -o=yaml'
    abbr --add --global kgingwoyaml 'kubectl get ingress --watch -o=yaml'
    abbr --add --global ksysgingwoyaml 'kubectl --namespace=kube-system get ingress --watch -o=yaml'
    abbr --add --global kgcmwoyaml 'kubectl get configmap --watch -o=yaml'
    abbr --add --global ksysgcmwoyaml 'kubectl --namespace=kube-system get configmap --watch -o=yaml'
    abbr --add --global kgsecwoyaml 'kubectl get secret --watch -o=yaml'
    abbr --add --global ksysgsecwoyaml 'kubectl --namespace=kube-system get secret --watch -o=yaml'
    abbr --add --global kgnowoyaml 'kubectl get nodes --watch -o=yaml'
    abbr --add --global kgnswoyaml 'kubectl get namespaces --watch -o=yaml'
    abbr --add --global kgowideall 'kubectl get -o=wide --all-namespaces'
    abbr --add --global kgpoowideall 'kubectl get pods -o=wide --all-namespaces'
    abbr --add --global kgdepowideall 'kubectl get deployment -o=wide --all-namespaces'
    abbr --add --global kgsvcowideall 'kubectl get service -o=wide --all-namespaces'
    abbr --add --global kgingowideall 'kubectl get ingress -o=wide --all-namespaces'
    abbr --add --global kgcmowideall 'kubectl get configmap -o=wide --all-namespaces'
    abbr --add --global kgsecowideall 'kubectl get secret -o=wide --all-namespaces'
    abbr --add --global kgnsowideall 'kubectl get namespaces -o=wide --all-namespaces'
    abbr --add --global kgallowide 'kubectl get --all-namespaces -o=wide'
    abbr --add --global kgpoallowide 'kubectl get pods --all-namespaces -o=wide'
    abbr --add --global kgdepallowide 'kubectl get deployment --all-namespaces -o=wide'
    abbr --add --global kgsvcallowide 'kubectl get service --all-namespaces -o=wide'
    abbr --add --global kgingallowide 'kubectl get ingress --all-namespaces -o=wide'
    abbr --add --global kgcmallowide 'kubectl get configmap --all-namespaces -o=wide'
    abbr --add --global kgsecallowide 'kubectl get secret --all-namespaces -o=wide'
    abbr --add --global kgnsallowide 'kubectl get namespaces --all-namespaces -o=wide'
    abbr --add --global kgowidesl 'kubectl get -o=wide --show-labels'
    abbr --add --global ksysgowidesl 'kubectl --namespace=kube-system get -o=wide --show-labels'
    abbr --add --global kgpoowidesl 'kubectl get pods -o=wide --show-labels'
    abbr --add --global ksysgpoowidesl 'kubectl --namespace=kube-system get pods -o=wide --show-labels'
    abbr --add --global kgdepowidesl 'kubectl get deployment -o=wide --show-labels'
    abbr --add --global ksysgdepowidesl 'kubectl --namespace=kube-system get deployment -o=wide --show-labels'
    abbr --add --global kgslowide 'kubectl get --show-labels -o=wide'
    abbr --add --global ksysgslowide 'kubectl --namespace=kube-system get --show-labels -o=wide'
    abbr --add --global kgposlowide 'kubectl get pods --show-labels -o=wide'
    abbr --add --global ksysgposlowide 'kubectl --namespace=kube-system get pods --show-labels -o=wide'
    abbr --add --global kgdepslowide 'kubectl get deployment --show-labels -o=wide'
    abbr --add --global ksysgdepslowide 'kubectl --namespace=kube-system get deployment --show-labels -o=wide'
    abbr --add --global kgwowide 'kubectl get --watch -o=wide'
    abbr --add --global ksysgwowide 'kubectl --namespace=kube-system get --watch -o=wide'
    abbr --add --global kgpowowide 'kubectl get pods --watch -o=wide'
    abbr --add --global ksysgpowowide 'kubectl --namespace=kube-system get pods --watch -o=wide'
    abbr --add --global kgdepwowide 'kubectl get deployment --watch -o=wide'
    abbr --add --global ksysgdepwowide 'kubectl --namespace=kube-system get deployment --watch -o=wide'
    abbr --add --global kgsvcwowide 'kubectl get service --watch -o=wide'
    abbr --add --global ksysgsvcwowide 'kubectl --namespace=kube-system get service --watch -o=wide'
    abbr --add --global kgingwowide 'kubectl get ingress --watch -o=wide'
    abbr --add --global ksysgingwowide 'kubectl --namespace=kube-system get ingress --watch -o=wide'
    abbr --add --global kgcmwowide 'kubectl get configmap --watch -o=wide'
    abbr --add --global ksysgcmwowide 'kubectl --namespace=kube-system get configmap --watch -o=wide'
    abbr --add --global kgsecwowide 'kubectl get secret --watch -o=wide'
    abbr --add --global ksysgsecwowide 'kubectl --namespace=kube-system get secret --watch -o=wide'
    abbr --add --global kgnowowide 'kubectl get nodes --watch -o=wide'
    abbr --add --global kgnswowide 'kubectl get namespaces --watch -o=wide'
    abbr --add --global kgojsonall 'kubectl get -o=json --all-namespaces'
    abbr --add --global kgpoojsonall 'kubectl get pods -o=json --all-namespaces'
    abbr --add --global kgdepojsonall 'kubectl get deployment -o=json --all-namespaces'
    abbr --add --global kgsvcojsonall 'kubectl get service -o=json --all-namespaces'
    abbr --add --global kgingojsonall 'kubectl get ingress -o=json --all-namespaces'
    abbr --add --global kgcmojsonall 'kubectl get configmap -o=json --all-namespaces'
    abbr --add --global kgsecojsonall 'kubectl get secret -o=json --all-namespaces'
    abbr --add --global kgnsojsonall 'kubectl get namespaces -o=json --all-namespaces'
    abbr --add --global kgallojson 'kubectl get --all-namespaces -o=json'
    abbr --add --global kgpoallojson 'kubectl get pods --all-namespaces -o=json'
    abbr --add --global kgdepallojson 'kubectl get deployment --all-namespaces -o=json'
    abbr --add --global kgsvcallojson 'kubectl get service --all-namespaces -o=json'
    abbr --add --global kgingallojson 'kubectl get ingress --all-namespaces -o=json'
    abbr --add --global kgcmallojson 'kubectl get configmap --all-namespaces -o=json'
    abbr --add --global kgsecallojson 'kubectl get secret --all-namespaces -o=json'
    abbr --add --global kgnsallojson 'kubectl get namespaces --all-namespaces -o=json'
    abbr --add --global kgwojson 'kubectl get --watch -o=json'
    abbr --add --global ksysgwojson 'kubectl --namespace=kube-system get --watch -o=json'
    abbr --add --global kgpowojson 'kubectl get pods --watch -o=json'
    abbr --add --global ksysgpowojson 'kubectl --namespace=kube-system get pods --watch -o=json'
    abbr --add --global kgdepwojson 'kubectl get deployment --watch -o=json'
    abbr --add --global ksysgdepwojson 'kubectl --namespace=kube-system get deployment --watch -o=json'
    abbr --add --global kgsvcwojson 'kubectl get service --watch -o=json'
    abbr --add --global ksysgsvcwojson 'kubectl --namespace=kube-system get service --watch -o=json'
    abbr --add --global kgingwojson 'kubectl get ingress --watch -o=json'
    abbr --add --global ksysgingwojson 'kubectl --namespace=kube-system get ingress --watch -o=json'
    abbr --add --global kgcmwojson 'kubectl get configmap --watch -o=json'
    abbr --add --global ksysgcmwojson 'kubectl --namespace=kube-system get configmap --watch -o=json'
    abbr --add --global kgsecwojson 'kubectl get secret --watch -o=json'
    abbr --add --global ksysgsecwojson 'kubectl --namespace=kube-system get secret --watch -o=json'
    abbr --add --global kgnowojson 'kubectl get nodes --watch -o=json'
    abbr --add --global kgnswojson 'kubectl get namespaces --watch -o=json'
    abbr --add --global kgallsl 'kubectl get --all-namespaces --show-labels'
    abbr --add --global kgpoallsl 'kubectl get pods --all-namespaces --show-labels'
    abbr --add --global kgdepallsl 'kubectl get deployment --all-namespaces --show-labels'
    abbr --add --global kgslall 'kubectl get --show-labels --all-namespaces'
    abbr --add --global kgposlall 'kubectl get pods --show-labels --all-namespaces'
    abbr --add --global kgdepslall 'kubectl get deployment --show-labels --all-namespaces'
    abbr --add --global kgallw 'kubectl get --all-namespaces --watch'
    abbr --add --global kgpoallw 'kubectl get pods --all-namespaces --watch'
    abbr --add --global kgdepallw 'kubectl get deployment --all-namespaces --watch'
    abbr --add --global kgsvcallw 'kubectl get service --all-namespaces --watch'
    abbr --add --global kgingallw 'kubectl get ingress --all-namespaces --watch'
    abbr --add --global kgcmallw 'kubectl get configmap --all-namespaces --watch'
    abbr --add --global kgsecallw 'kubectl get secret --all-namespaces --watch'
    abbr --add --global kgnsallw 'kubectl get namespaces --all-namespaces --watch'
    abbr --add --global kgwall 'kubectl get --watch --all-namespaces'
    abbr --add --global kgpowall 'kubectl get pods --watch --all-namespaces'
    abbr --add --global kgdepwall 'kubectl get deployment --watch --all-namespaces'
    abbr --add --global kgsvcwall 'kubectl get service --watch --all-namespaces'
    abbr --add --global kgingwall 'kubectl get ingress --watch --all-namespaces'
    abbr --add --global kgcmwall 'kubectl get configmap --watch --all-namespaces'
    abbr --add --global kgsecwall 'kubectl get secret --watch --all-namespaces'
    abbr --add --global kgnswall 'kubectl get namespaces --watch --all-namespaces'
    abbr --add --global kgslw 'kubectl get --show-labels --watch'
    abbr --add --global ksysgslw 'kubectl --namespace=kube-system get --show-labels --watch'
    abbr --add --global kgposlw 'kubectl get pods --show-labels --watch'
    abbr --add --global ksysgposlw 'kubectl --namespace=kube-system get pods --show-labels --watch'
    abbr --add --global kgdepslw 'kubectl get deployment --show-labels --watch'
    abbr --add --global ksysgdepslw 'kubectl --namespace=kube-system get deployment --show-labels --watch'
    abbr --add --global kgwsl 'kubectl get --watch --show-labels'
    abbr --add --global ksysgwsl 'kubectl --namespace=kube-system get --watch --show-labels'
    abbr --add --global kgpowsl 'kubectl get pods --watch --show-labels'
    abbr --add --global ksysgpowsl 'kubectl --namespace=kube-system get pods --watch --show-labels'
    abbr --add --global kgdepwsl 'kubectl get deployment --watch --show-labels'
    abbr --add --global ksysgdepwsl 'kubectl --namespace=kube-system get deployment --watch --show-labels'
    abbr --add --global kgallwoyaml 'kubectl get --all-namespaces --watch -o=yaml'
    abbr --add --global kgpoallwoyaml 'kubectl get pods --all-namespaces --watch -o=yaml'
    abbr --add --global kgdepallwoyaml 'kubectl get deployment --all-namespaces --watch -o=yaml'
    abbr --add --global kgsvcallwoyaml 'kubectl get service --all-namespaces --watch -o=yaml'
    abbr --add --global kgingallwoyaml 'kubectl get ingress --all-namespaces --watch -o=yaml'
    abbr --add --global kgcmallwoyaml 'kubectl get configmap --all-namespaces --watch -o=yaml'
    abbr --add --global kgsecallwoyaml 'kubectl get secret --all-namespaces --watch -o=yaml'
    abbr --add --global kgnsallwoyaml 'kubectl get namespaces --all-namespaces --watch -o=yaml'
    abbr --add --global kgwoyamlall 'kubectl get --watch -o=yaml --all-namespaces'
    abbr --add --global kgpowoyamlall 'kubectl get pods --watch -o=yaml --all-namespaces'
    abbr --add --global kgdepwoyamlall 'kubectl get deployment --watch -o=yaml --all-namespaces'
    abbr --add --global kgsvcwoyamlall 'kubectl get service --watch -o=yaml --all-namespaces'
    abbr --add --global kgingwoyamlall 'kubectl get ingress --watch -o=yaml --all-namespaces'
    abbr --add --global kgcmwoyamlall 'kubectl get configmap --watch -o=yaml --all-namespaces'
    abbr --add --global kgsecwoyamlall 'kubectl get secret --watch -o=yaml --all-namespaces'
    abbr --add --global kgnswoyamlall 'kubectl get namespaces --watch -o=yaml --all-namespaces'
    abbr --add --global kgwalloyaml 'kubectl get --watch --all-namespaces -o=yaml'
    abbr --add --global kgpowalloyaml 'kubectl get pods --watch --all-namespaces -o=yaml'
    abbr --add --global kgdepwalloyaml 'kubectl get deployment --watch --all-namespaces -o=yaml'
    abbr --add --global kgsvcwalloyaml 'kubectl get service --watch --all-namespaces -o=yaml'
    abbr --add --global kgingwalloyaml 'kubectl get ingress --watch --all-namespaces -o=yaml'
    abbr --add --global kgcmwalloyaml 'kubectl get configmap --watch --all-namespaces -o=yaml'
    abbr --add --global kgsecwalloyaml 'kubectl get secret --watch --all-namespaces -o=yaml'
    abbr --add --global kgnswalloyaml 'kubectl get namespaces --watch --all-namespaces -o=yaml'
    abbr --add --global kgowideallsl 'kubectl get -o=wide --all-namespaces --show-labels'
    abbr --add --global kgpoowideallsl 'kubectl get pods -o=wide --all-namespaces --show-labels'
    abbr --add --global kgdepowideallsl 'kubectl get deployment -o=wide --all-namespaces --show-labels'
    abbr --add --global kgowideslall 'kubectl get -o=wide --show-labels --all-namespaces'
    abbr --add --global kgpoowideslall 'kubectl get pods -o=wide --show-labels --all-namespaces'
    abbr --add --global kgdepowideslall 'kubectl get deployment -o=wide --show-labels --all-namespaces'
    abbr --add --global kgallowidesl 'kubectl get --all-namespaces -o=wide --show-labels'
    abbr --add --global kgpoallowidesl 'kubectl get pods --all-namespaces -o=wide --show-labels'
    abbr --add --global kgdepallowidesl 'kubectl get deployment --all-namespaces -o=wide --show-labels'
    abbr --add --global kgallslowide 'kubectl get --all-namespaces --show-labels -o=wide'
    abbr --add --global kgpoallslowide 'kubectl get pods --all-namespaces --show-labels -o=wide'
    abbr --add --global kgdepallslowide 'kubectl get deployment --all-namespaces --show-labels -o=wide'
    abbr --add --global kgslowideall 'kubectl get --show-labels -o=wide --all-namespaces'
    abbr --add --global kgposlowideall 'kubectl get pods --show-labels -o=wide --all-namespaces'
    abbr --add --global kgdepslowideall 'kubectl get deployment --show-labels -o=wide --all-namespaces'
    abbr --add --global kgslallowide 'kubectl get --show-labels --all-namespaces -o=wide'
    abbr --add --global kgposlallowide 'kubectl get pods --show-labels --all-namespaces -o=wide'
    abbr --add --global kgdepslallowide 'kubectl get deployment --show-labels --all-namespaces -o=wide'
    abbr --add --global kgallwowide 'kubectl get --all-namespaces --watch -o=wide'
    abbr --add --global kgpoallwowide 'kubectl get pods --all-namespaces --watch -o=wide'
    abbr --add --global kgdepallwowide 'kubectl get deployment --all-namespaces --watch -o=wide'
    abbr --add --global kgsvcallwowide 'kubectl get service --all-namespaces --watch -o=wide'
    abbr --add --global kgingallwowide 'kubectl get ingress --all-namespaces --watch -o=wide'
    abbr --add --global kgcmallwowide 'kubectl get configmap --all-namespaces --watch -o=wide'
    abbr --add --global kgsecallwowide 'kubectl get secret --all-namespaces --watch -o=wide'
    abbr --add --global kgnsallwowide 'kubectl get namespaces --all-namespaces --watch -o=wide'
    abbr --add --global kgwowideall 'kubectl get --watch -o=wide --all-namespaces'
    abbr --add --global kgpowowideall 'kubectl get pods --watch -o=wide --all-namespaces'
    abbr --add --global kgdepwowideall 'kubectl get deployment --watch -o=wide --all-namespaces'
    abbr --add --global kgsvcwowideall 'kubectl get service --watch -o=wide --all-namespaces'
    abbr --add --global kgingwowideall 'kubectl get ingress --watch -o=wide --all-namespaces'
    abbr --add --global kgcmwowideall 'kubectl get configmap --watch -o=wide --all-namespaces'
    abbr --add --global kgsecwowideall 'kubectl get secret --watch -o=wide --all-namespaces'
    abbr --add --global kgnswowideall 'kubectl get namespaces --watch -o=wide --all-namespaces'
    abbr --add --global kgwallowide 'kubectl get --watch --all-namespaces -o=wide'
    abbr --add --global kgpowallowide 'kubectl get pods --watch --all-namespaces -o=wide'
    abbr --add --global kgdepwallowide 'kubectl get deployment --watch --all-namespaces -o=wide'
    abbr --add --global kgsvcwallowide 'kubectl get service --watch --all-namespaces -o=wide'
    abbr --add --global kgingwallowide 'kubectl get ingress --watch --all-namespaces -o=wide'
    abbr --add --global kgcmwallowide 'kubectl get configmap --watch --all-namespaces -o=wide'
    abbr --add --global kgsecwallowide 'kubectl get secret --watch --all-namespaces -o=wide'
    abbr --add --global kgnswallowide 'kubectl get namespaces --watch --all-namespaces -o=wide'
    abbr --add --global kgslwowide 'kubectl get --show-labels --watch -o=wide'
    abbr --add --global ksysgslwowide 'kubectl --namespace=kube-system get --show-labels --watch -o=wide'
    abbr --add --global kgposlwowide 'kubectl get pods --show-labels --watch -o=wide'
    abbr --add --global ksysgposlwowide 'kubectl --namespace=kube-system get pods --show-labels --watch -o=wide'
    abbr --add --global kgdepslwowide 'kubectl get deployment --show-labels --watch -o=wide'
    abbr --add --global ksysgdepslwowide 'kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide'
    abbr --add --global kgwowidesl 'kubectl get --watch -o=wide --show-labels'
    abbr --add --global ksysgwowidesl 'kubectl --namespace=kube-system get --watch -o=wide --show-labels'
    abbr --add --global kgpowowidesl 'kubectl get pods --watch -o=wide --show-labels'
    abbr --add --global ksysgpowowidesl 'kubectl --namespace=kube-system get pods --watch -o=wide --show-labels'
    abbr --add --global kgdepwowidesl 'kubectl get deployment --watch -o=wide --show-labels'
    abbr --add --global ksysgdepwowidesl 'kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels'
    abbr --add --global kgwslowide 'kubectl get --watch --show-labels -o=wide'
    abbr --add --global ksysgwslowide 'kubectl --namespace=kube-system get --watch --show-labels -o=wide'
    abbr --add --global kgpowslowide 'kubectl get pods --watch --show-labels -o=wide'
    abbr --add --global ksysgpowslowide 'kubectl --namespace=kube-system get pods --watch --show-labels -o=wide'
    abbr --add --global kgdepwslowide 'kubectl get deployment --watch --show-labels -o=wide'
    abbr --add --global ksysgdepwslowide 'kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide'
    abbr --add --global kgallwojson 'kubectl get --all-namespaces --watch -o=json'
    abbr --add --global kgpoallwojson 'kubectl get pods --all-namespaces --watch -o=json'
    abbr --add --global kgdepallwojson 'kubectl get deployment --all-namespaces --watch -o=json'
    abbr --add --global kgsvcallwojson 'kubectl get service --all-namespaces --watch -o=json'
    abbr --add --global kgingallwojson 'kubectl get ingress --all-namespaces --watch -o=json'
    abbr --add --global kgcmallwojson 'kubectl get configmap --all-namespaces --watch -o=json'
    abbr --add --global kgsecallwojson 'kubectl get secret --all-namespaces --watch -o=json'
    abbr --add --global kgnsallwojson 'kubectl get namespaces --all-namespaces --watch -o=json'
    abbr --add --global kgwojsonall 'kubectl get --watch -o=json --all-namespaces'
    abbr --add --global kgpowojsonall 'kubectl get pods --watch -o=json --all-namespaces'
    abbr --add --global kgdepwojsonall 'kubectl get deployment --watch -o=json --all-namespaces'
    abbr --add --global kgsvcwojsonall 'kubectl get service --watch -o=json --all-namespaces'
    abbr --add --global kgingwojsonall 'kubectl get ingress --watch -o=json --all-namespaces'
    abbr --add --global kgcmwojsonall 'kubectl get configmap --watch -o=json --all-namespaces'
    abbr --add --global kgsecwojsonall 'kubectl get secret --watch -o=json --all-namespaces'
    abbr --add --global kgnswojsonall 'kubectl get namespaces --watch -o=json --all-namespaces'
    abbr --add --global kgwallojson 'kubectl get --watch --all-namespaces -o=json'
    abbr --add --global kgpowallojson 'kubectl get pods --watch --all-namespaces -o=json'
    abbr --add --global kgdepwallojson 'kubectl get deployment --watch --all-namespaces -o=json'
    abbr --add --global kgsvcwallojson 'kubectl get service --watch --all-namespaces -o=json'
    abbr --add --global kgingwallojson 'kubectl get ingress --watch --all-namespaces -o=json'
    abbr --add --global kgcmwallojson 'kubectl get configmap --watch --all-namespaces -o=json'
    abbr --add --global kgsecwallojson 'kubectl get secret --watch --all-namespaces -o=json'
    abbr --add --global kgnswallojson 'kubectl get namespaces --watch --all-namespaces -o=json'
    abbr --add --global kgallslw 'kubectl get --all-namespaces --show-labels --watch'
    abbr --add --global kgpoallslw 'kubectl get pods --all-namespaces --show-labels --watch'
    abbr --add --global kgdepallslw 'kubectl get deployment --all-namespaces --show-labels --watch'
    abbr --add --global kgallwsl 'kubectl get --all-namespaces --watch --show-labels'
    abbr --add --global kgpoallwsl 'kubectl get pods --all-namespaces --watch --show-labels'
    abbr --add --global kgdepallwsl 'kubectl get deployment --all-namespaces --watch --show-labels'
    abbr --add --global kgslallw 'kubectl get --show-labels --all-namespaces --watch'
    abbr --add --global kgposlallw 'kubectl get pods --show-labels --all-namespaces --watch'
    abbr --add --global kgdepslallw 'kubectl get deployment --show-labels --all-namespaces --watch'
    abbr --add --global kgslwall 'kubectl get --show-labels --watch --all-namespaces'
    abbr --add --global kgposlwall 'kubectl get pods --show-labels --watch --all-namespaces'
    abbr --add --global kgdepslwall 'kubectl get deployment --show-labels --watch --all-namespaces'
    abbr --add --global kgwallsl 'kubectl get --watch --all-namespaces --show-labels'
    abbr --add --global kgpowallsl 'kubectl get pods --watch --all-namespaces --show-labels'
    abbr --add --global kgdepwallsl 'kubectl get deployment --watch --all-namespaces --show-labels'
    abbr --add --global kgwslall 'kubectl get --watch --show-labels --all-namespaces'
    abbr --add --global kgpowslall 'kubectl get pods --watch --show-labels --all-namespaces'
    abbr --add --global kgdepwslall 'kubectl get deployment --watch --show-labels --all-namespaces'
    abbr --add --global kgallslwowide 'kubectl get --all-namespaces --show-labels --watch -o=wide'
    abbr --add --global kgpoallslwowide 'kubectl get pods --all-namespaces --show-labels --watch -o=wide'
    abbr --add --global kgdepallslwowide 'kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
    abbr --add --global kgallwowidesl 'kubectl get --all-namespaces --watch -o=wide --show-labels'
    abbr --add --global kgpoallwowidesl 'kubectl get pods --all-namespaces --watch -o=wide --show-labels'
    abbr --add --global kgdepallwowidesl 'kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
    abbr --add --global kgallwslowide 'kubectl get --all-namespaces --watch --show-labels -o=wide'
    abbr --add --global kgpoallwslowide 'kubectl get pods --all-namespaces --watch --show-labels -o=wide'
    abbr --add --global kgdepallwslowide 'kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
    abbr --add --global kgslallwowide 'kubectl get --show-labels --all-namespaces --watch -o=wide'
    abbr --add --global kgposlallwowide 'kubectl get pods --show-labels --all-namespaces --watch -o=wide'
    abbr --add --global kgdepslallwowide 'kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
    abbr --add --global kgslwowideall 'kubectl get --show-labels --watch -o=wide --all-namespaces'
    abbr --add --global kgposlwowideall 'kubectl get pods --show-labels --watch -o=wide --all-namespaces'
    abbr --add --global kgdepslwowideall 'kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
    abbr --add --global kgslwallowide 'kubectl get --show-labels --watch --all-namespaces -o=wide'
    abbr --add --global kgposlwallowide 'kubectl get pods --show-labels --watch --all-namespaces -o=wide'
    abbr --add --global kgdepslwallowide 'kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
    abbr --add --global kgwowideallsl 'kubectl get --watch -o=wide --all-namespaces --show-labels'
    abbr --add --global kgpowowideallsl 'kubectl get pods --watch -o=wide --all-namespaces --show-labels'
    abbr --add --global kgdepwowideallsl 'kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
    abbr --add --global kgwowideslall 'kubectl get --watch -o=wide --show-labels --all-namespaces'
    abbr --add --global kgpowowideslall 'kubectl get pods --watch -o=wide --show-labels --all-namespaces'
    abbr --add --global kgdepwowideslall 'kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
    abbr --add --global kgwallowidesl 'kubectl get --watch --all-namespaces -o=wide --show-labels'
    abbr --add --global kgpowallowidesl 'kubectl get pods --watch --all-namespaces -o=wide --show-labels'
    abbr --add --global kgdepwallowidesl 'kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
    abbr --add --global kgwallslowide 'kubectl get --watch --all-namespaces --show-labels -o=wide'
    abbr --add --global kgpowallslowide 'kubectl get pods --watch --all-namespaces --show-labels -o=wide'
    abbr --add --global kgdepwallslowide 'kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
    abbr --add --global kgwslowideall 'kubectl get --watch --show-labels -o=wide --all-namespaces'
    abbr --add --global kgpowslowideall 'kubectl get pods --watch --show-labels -o=wide --all-namespaces'
    abbr --add --global kgdepwslowideall 'kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
    abbr --add --global kgwslallowide 'kubectl get --watch --show-labels --all-namespaces -o=wide'
    abbr --add --global kgpowslallowide 'kubectl get pods --watch --show-labels --all-namespaces -o=wide'
    abbr --add --global kgdepwslallowide 'kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
    abbr --add --global kgf 'kubectl get --recursive -f'
    abbr --add --global kdf 'kubectl describe --recursive -f'
    abbr --add --global krmf 'kubectl delete --recursive -f'
    abbr --add --global kgoyamlf 'kubectl get -o=yaml --recursive -f'
    abbr --add --global kgowidef 'kubectl get -o=wide --recursive -f'
    abbr --add --global kgojsonf 'kubectl get -o=json --recursive -f'
    abbr --add --global kgslf 'kubectl get --show-labels --recursive -f'
    abbr --add --global kgwf 'kubectl get --watch --recursive -f'
    abbr --add --global kgwoyamlf 'kubectl get --watch -o=yaml --recursive -f'
    abbr --add --global kgowideslf 'kubectl get -o=wide --show-labels --recursive -f'
    abbr --add --global kgslowidef 'kubectl get --show-labels -o=wide --recursive -f'
    abbr --add --global kgwowidef 'kubectl get --watch -o=wide --recursive -f'
    abbr --add --global kgwojsonf 'kubectl get --watch -o=json --recursive -f'
    abbr --add --global kgslwf 'kubectl get --show-labels --watch --recursive -f'
    abbr --add --global kgwslf 'kubectl get --watch --show-labels --recursive -f'
    abbr --add --global kgslwowidef 'kubectl get --show-labels --watch -o=wide --recursive -f'
    abbr --add --global kgwowideslf 'kubectl get --watch -o=wide --show-labels --recursive -f'
    abbr --add --global kgwslowidef 'kubectl get --watch --show-labels -o=wide --recursive -f'
    abbr --add --global kgl 'kubectl get -l'
    abbr --add --global ksysgl 'kubectl --namespace=kube-system get -l'
    abbr --add --global kdl 'kubectl describe -l'
    abbr --add --global ksysdl 'kubectl --namespace=kube-system describe -l'
    abbr --add --global krml 'kubectl delete -l'
    abbr --add --global ksysrml 'kubectl --namespace=kube-system delete -l'
    abbr --add --global kgpol 'kubectl get pods -l'
    abbr --add --global ksysgpol 'kubectl --namespace=kube-system get pods -l'
    abbr --add --global kdpol 'kubectl describe pods -l'
    abbr --add --global ksysdpol 'kubectl --namespace=kube-system describe pods -l'
    abbr --add --global krmpol 'kubectl delete pods -l'
    abbr --add --global ksysrmpol 'kubectl --namespace=kube-system delete pods -l'
    abbr --add --global kgdepl 'kubectl get deployment -l'
    abbr --add --global ksysgdepl 'kubectl --namespace=kube-system get deployment -l'
    abbr --add --global kddepl 'kubectl describe deployment -l'
    abbr --add --global ksysddepl 'kubectl --namespace=kube-system describe deployment -l'
    abbr --add --global krmdepl 'kubectl delete deployment -l'
    abbr --add --global ksysrmdepl 'kubectl --namespace=kube-system delete deployment -l'
    abbr --add --global kgsvcl 'kubectl get service -l'
    abbr --add --global ksysgsvcl 'kubectl --namespace=kube-system get service -l'
    abbr --add --global kdsvcl 'kubectl describe service -l'
    abbr --add --global ksysdsvcl 'kubectl --namespace=kube-system describe service -l'
    abbr --add --global krmsvcl 'kubectl delete service -l'
    abbr --add --global ksysrmsvcl 'kubectl --namespace=kube-system delete service -l'
    abbr --add --global kgingl 'kubectl get ingress -l'
    abbr --add --global ksysgingl 'kubectl --namespace=kube-system get ingress -l'
    abbr --add --global kdingl 'kubectl describe ingress -l'
    abbr --add --global ksysdingl 'kubectl --namespace=kube-system describe ingress -l'
    abbr --add --global krmingl 'kubectl delete ingress -l'
    abbr --add --global ksysrmingl 'kubectl --namespace=kube-system delete ingress -l'
    abbr --add --global kgcml 'kubectl get configmap -l'
    abbr --add --global ksysgcml 'kubectl --namespace=kube-system get configmap -l'
    abbr --add --global kdcml 'kubectl describe configmap -l'
    abbr --add --global ksysdcml 'kubectl --namespace=kube-system describe configmap -l'
    abbr --add --global krmcml 'kubectl delete configmap -l'
    abbr --add --global ksysrmcml 'kubectl --namespace=kube-system delete configmap -l'
    abbr --add --global kgsecl 'kubectl get secret -l'
    abbr --add --global ksysgsecl 'kubectl --namespace=kube-system get secret -l'
    abbr --add --global kdsecl 'kubectl describe secret -l'
    abbr --add --global ksysdsecl 'kubectl --namespace=kube-system describe secret -l'
    abbr --add --global krmsecl 'kubectl delete secret -l'
    abbr --add --global ksysrmsecl 'kubectl --namespace=kube-system delete secret -l'
    abbr --add --global kgnol 'kubectl get nodes -l'
    abbr --add --global kdnol 'kubectl describe nodes -l'
    abbr --add --global kgnsl 'kubectl get namespaces -l'
    abbr --add --global kdnsl 'kubectl describe namespaces -l'
    abbr --add --global krmnsl 'kubectl delete namespaces -l'
    abbr --add --global kgoyamll 'kubectl get -o=yaml -l'
    abbr --add --global ksysgoyamll 'kubectl --namespace=kube-system get -o=yaml -l'
    abbr --add --global kgpooyamll 'kubectl get pods -o=yaml -l'
    abbr --add --global ksysgpooyamll 'kubectl --namespace=kube-system get pods -o=yaml -l'
    abbr --add --global kgdepoyamll 'kubectl get deployment -o=yaml -l'
    abbr --add --global ksysgdepoyamll 'kubectl --namespace=kube-system get deployment -o=yaml -l'
    abbr --add --global kgsvcoyamll 'kubectl get service -o=yaml -l'
    abbr --add --global ksysgsvcoyamll 'kubectl --namespace=kube-system get service -o=yaml -l'
    abbr --add --global kgingoyamll 'kubectl get ingress -o=yaml -l'
    abbr --add --global ksysgingoyamll 'kubectl --namespace=kube-system get ingress -o=yaml -l'
    abbr --add --global kgcmoyamll 'kubectl get configmap -o=yaml -l'
    abbr --add --global ksysgcmoyamll 'kubectl --namespace=kube-system get configmap -o=yaml -l'
    abbr --add --global kgsecoyamll 'kubectl get secret -o=yaml -l'
    abbr --add --global ksysgsecoyamll 'kubectl --namespace=kube-system get secret -o=yaml -l'
    abbr --add --global kgnooyamll 'kubectl get nodes -o=yaml -l'
    abbr --add --global kgnsoyamll 'kubectl get namespaces -o=yaml -l'
    abbr --add --global kgowidel 'kubectl get -o=wide -l'
    abbr --add --global ksysgowidel 'kubectl --namespace=kube-system get -o=wide -l'
    abbr --add --global kgpoowidel 'kubectl get pods -o=wide -l'
    abbr --add --global ksysgpoowidel 'kubectl --namespace=kube-system get pods -o=wide -l'
    abbr --add --global kgdepowidel 'kubectl get deployment -o=wide -l'
    abbr --add --global ksysgdepowidel 'kubectl --namespace=kube-system get deployment -o=wide -l'
    abbr --add --global kgsvcowidel 'kubectl get service -o=wide -l'
    abbr --add --global ksysgsvcowidel 'kubectl --namespace=kube-system get service -o=wide -l'
    abbr --add --global kgingowidel 'kubectl get ingress -o=wide -l'
    abbr --add --global ksysgingowidel 'kubectl --namespace=kube-system get ingress -o=wide -l'
    abbr --add --global kgcmowidel 'kubectl get configmap -o=wide -l'
    abbr --add --global ksysgcmowidel 'kubectl --namespace=kube-system get configmap -o=wide -l'
    abbr --add --global kgsecowidel 'kubectl get secret -o=wide -l'
    abbr --add --global ksysgsecowidel 'kubectl --namespace=kube-system get secret -o=wide -l'
    abbr --add --global kgnoowidel 'kubectl get nodes -o=wide -l'
    abbr --add --global kgnsowidel 'kubectl get namespaces -o=wide -l'
    abbr --add --global kgojsonl 'kubectl get -o=json -l'
    abbr --add --global ksysgojsonl 'kubectl --namespace=kube-system get -o=json -l'
    abbr --add --global kgpoojsonl 'kubectl get pods -o=json -l'
    abbr --add --global ksysgpoojsonl 'kubectl --namespace=kube-system get pods -o=json -l'
    abbr --add --global kgdepojsonl 'kubectl get deployment -o=json -l'
    abbr --add --global ksysgdepojsonl 'kubectl --namespace=kube-system get deployment -o=json -l'
    abbr --add --global kgsvcojsonl 'kubectl get service -o=json -l'
    abbr --add --global ksysgsvcojsonl 'kubectl --namespace=kube-system get service -o=json -l'
    abbr --add --global kgingojsonl 'kubectl get ingress -o=json -l'
    abbr --add --global ksysgingojsonl 'kubectl --namespace=kube-system get ingress -o=json -l'
    abbr --add --global kgcmojsonl 'kubectl get configmap -o=json -l'
    abbr --add --global ksysgcmojsonl 'kubectl --namespace=kube-system get configmap -o=json -l'
    abbr --add --global kgsecojsonl 'kubectl get secret -o=json -l'
    abbr --add --global ksysgsecojsonl 'kubectl --namespace=kube-system get secret -o=json -l'
    abbr --add --global kgnoojsonl 'kubectl get nodes -o=json -l'
    abbr --add --global kgnsojsonl 'kubectl get namespaces -o=json -l'
    abbr --add --global kgsll 'kubectl get --show-labels -l'
    abbr --add --global ksysgsll 'kubectl --namespace=kube-system get --show-labels -l'
    abbr --add --global kgposll 'kubectl get pods --show-labels -l'
    abbr --add --global ksysgposll 'kubectl --namespace=kube-system get pods --show-labels -l'
    abbr --add --global kgdepsll 'kubectl get deployment --show-labels -l'
    abbr --add --global ksysgdepsll 'kubectl --namespace=kube-system get deployment --show-labels -l'
    abbr --add --global kgwl 'kubectl get --watch -l'
    abbr --add --global ksysgwl 'kubectl --namespace=kube-system get --watch -l'
    abbr --add --global kgpowl 'kubectl get pods --watch -l'
    abbr --add --global ksysgpowl 'kubectl --namespace=kube-system get pods --watch -l'
    abbr --add --global kgdepwl 'kubectl get deployment --watch -l'
    abbr --add --global ksysgdepwl 'kubectl --namespace=kube-system get deployment --watch -l'
    abbr --add --global kgsvcwl 'kubectl get service --watch -l'
    abbr --add --global ksysgsvcwl 'kubectl --namespace=kube-system get service --watch -l'
    abbr --add --global kgingwl 'kubectl get ingress --watch -l'
    abbr --add --global ksysgingwl 'kubectl --namespace=kube-system get ingress --watch -l'
    abbr --add --global kgcmwl 'kubectl get configmap --watch -l'
    abbr --add --global ksysgcmwl 'kubectl --namespace=kube-system get configmap --watch -l'
    abbr --add --global kgsecwl 'kubectl get secret --watch -l'
    abbr --add --global ksysgsecwl 'kubectl --namespace=kube-system get secret --watch -l'
    abbr --add --global kgnowl 'kubectl get nodes --watch -l'
    abbr --add --global kgnswl 'kubectl get namespaces --watch -l'
    abbr --add --global kgwoyamll 'kubectl get --watch -o=yaml -l'
    abbr --add --global ksysgwoyamll 'kubectl --namespace=kube-system get --watch -o=yaml -l'
    abbr --add --global kgpowoyamll 'kubectl get pods --watch -o=yaml -l'
    abbr --add --global ksysgpowoyamll 'kubectl --namespace=kube-system get pods --watch -o=yaml -l'
    abbr --add --global kgdepwoyamll 'kubectl get deployment --watch -o=yaml -l'
    abbr --add --global ksysgdepwoyamll 'kubectl --namespace=kube-system get deployment --watch -o=yaml -l'
    abbr --add --global kgsvcwoyamll 'kubectl get service --watch -o=yaml -l'
    abbr --add --global ksysgsvcwoyamll 'kubectl --namespace=kube-system get service --watch -o=yaml -l'
    abbr --add --global kgingwoyamll 'kubectl get ingress --watch -o=yaml -l'
    abbr --add --global ksysgingwoyamll 'kubectl --namespace=kube-system get ingress --watch -o=yaml -l'
    abbr --add --global kgcmwoyamll 'kubectl get configmap --watch -o=yaml -l'
    abbr --add --global ksysgcmwoyamll 'kubectl --namespace=kube-system get configmap --watch -o=yaml -l'
    abbr --add --global kgsecwoyamll 'kubectl get secret --watch -o=yaml -l'
    abbr --add --global ksysgsecwoyamll 'kubectl --namespace=kube-system get secret --watch -o=yaml -l'
    abbr --add --global kgnowoyamll 'kubectl get nodes --watch -o=yaml -l'
    abbr --add --global kgnswoyamll 'kubectl get namespaces --watch -o=yaml -l'
    abbr --add --global kgowidesll 'kubectl get -o=wide --show-labels -l'
    abbr --add --global ksysgowidesll 'kubectl --namespace=kube-system get -o=wide --show-labels -l'
    abbr --add --global kgpoowidesll 'kubectl get pods -o=wide --show-labels -l'
    abbr --add --global ksysgpoowidesll 'kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
    abbr --add --global kgdepowidesll 'kubectl get deployment -o=wide --show-labels -l'
    abbr --add --global ksysgdepowidesll 'kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
    abbr --add --global kgslowidel 'kubectl get --show-labels -o=wide -l'
    abbr --add --global ksysgslowidel 'kubectl --namespace=kube-system get --show-labels -o=wide -l'
    abbr --add --global kgposlowidel 'kubectl get pods --show-labels -o=wide -l'
    abbr --add --global ksysgposlowidel 'kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
    abbr --add --global kgdepslowidel 'kubectl get deployment --show-labels -o=wide -l'
    abbr --add --global ksysgdepslowidel 'kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
    abbr --add --global kgwowidel 'kubectl get --watch -o=wide -l'
    abbr --add --global ksysgwowidel 'kubectl --namespace=kube-system get --watch -o=wide -l'
    abbr --add --global kgpowowidel 'kubectl get pods --watch -o=wide -l'
    abbr --add --global ksysgpowowidel 'kubectl --namespace=kube-system get pods --watch -o=wide -l'
    abbr --add --global kgdepwowidel 'kubectl get deployment --watch -o=wide -l'
    abbr --add --global ksysgdepwowidel 'kubectl --namespace=kube-system get deployment --watch -o=wide -l'
    abbr --add --global kgsvcwowidel 'kubectl get service --watch -o=wide -l'
    abbr --add --global ksysgsvcwowidel 'kubectl --namespace=kube-system get service --watch -o=wide -l'
    abbr --add --global kgingwowidel 'kubectl get ingress --watch -o=wide -l'
    abbr --add --global ksysgingwowidel 'kubectl --namespace=kube-system get ingress --watch -o=wide -l'
    abbr --add --global kgcmwowidel 'kubectl get configmap --watch -o=wide -l'
    abbr --add --global ksysgcmwowidel 'kubectl --namespace=kube-system get configmap --watch -o=wide -l'
    abbr --add --global kgsecwowidel 'kubectl get secret --watch -o=wide -l'
    abbr --add --global ksysgsecwowidel 'kubectl --namespace=kube-system get secret --watch -o=wide -l'
    abbr --add --global kgnowowidel 'kubectl get nodes --watch -o=wide -l'
    abbr --add --global kgnswowidel 'kubectl get namespaces --watch -o=wide -l'
    abbr --add --global kgwojsonl 'kubectl get --watch -o=json -l'
    abbr --add --global ksysgwojsonl 'kubectl --namespace=kube-system get --watch -o=json -l'
    abbr --add --global kgpowojsonl 'kubectl get pods --watch -o=json -l'
    abbr --add --global ksysgpowojsonl 'kubectl --namespace=kube-system get pods --watch -o=json -l'
    abbr --add --global kgdepwojsonl 'kubectl get deployment --watch -o=json -l'
    abbr --add --global ksysgdepwojsonl 'kubectl --namespace=kube-system get deployment --watch -o=json -l'
    abbr --add --global kgsvcwojsonl 'kubectl get service --watch -o=json -l'
    abbr --add --global ksysgsvcwojsonl 'kubectl --namespace=kube-system get service --watch -o=json -l'
    abbr --add --global kgingwojsonl 'kubectl get ingress --watch -o=json -l'
    abbr --add --global ksysgingwojsonl 'kubectl --namespace=kube-system get ingress --watch -o=json -l'
    abbr --add --global kgcmwojsonl 'kubectl get configmap --watch -o=json -l'
    abbr --add --global ksysgcmwojsonl 'kubectl --namespace=kube-system get configmap --watch -o=json -l'
    abbr --add --global kgsecwojsonl 'kubectl get secret --watch -o=json -l'
    abbr --add --global ksysgsecwojsonl 'kubectl --namespace=kube-system get secret --watch -o=json -l'
    abbr --add --global kgnowojsonl 'kubectl get nodes --watch -o=json -l'
    abbr --add --global kgnswojsonl 'kubectl get namespaces --watch -o=json -l'
    abbr --add --global kgslwl 'kubectl get --show-labels --watch -l'
    abbr --add --global ksysgslwl 'kubectl --namespace=kube-system get --show-labels --watch -l'
    abbr --add --global kgposlwl 'kubectl get pods --show-labels --watch -l'
    abbr --add --global ksysgposlwl 'kubectl --namespace=kube-system get pods --show-labels --watch -l'
    abbr --add --global kgdepslwl 'kubectl get deployment --show-labels --watch -l'
    abbr --add --global ksysgdepslwl 'kubectl --namespace=kube-system get deployment --show-labels --watch -l'
    abbr --add --global kgwsll 'kubectl get --watch --show-labels -l'
    abbr --add --global ksysgwsll 'kubectl --namespace=kube-system get --watch --show-labels -l'
    abbr --add --global kgpowsll 'kubectl get pods --watch --show-labels -l'
    abbr --add --global ksysgpowsll 'kubectl --namespace=kube-system get pods --watch --show-labels -l'
    abbr --add --global kgdepwsll 'kubectl get deployment --watch --show-labels -l'
    abbr --add --global ksysgdepwsll 'kubectl --namespace=kube-system get deployment --watch --show-labels -l'
    abbr --add --global kgslwowidel 'kubectl get --show-labels --watch -o=wide -l'
    abbr --add --global ksysgslwowidel 'kubectl --namespace=kube-system get --show-labels --watch -o=wide -l'
    abbr --add --global kgposlwowidel 'kubectl get pods --show-labels --watch -o=wide -l'
    abbr --add --global ksysgposlwowidel 'kubectl --namespace=kube-system get pods --show-labels --watch -o=wide -l'
    abbr --add --global kgdepslwowidel 'kubectl get deployment --show-labels --watch -o=wide -l'
    abbr --add --global ksysgdepslwowidel 'kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
    abbr --add --global kgwowidesll 'kubectl get --watch -o=wide --show-labels -l'
    abbr --add --global ksysgwowidesll 'kubectl --namespace=kube-system get --watch -o=wide --show-labels -l'
    abbr --add --global kgpowowidesll 'kubectl get pods --watch -o=wide --show-labels -l'
    abbr --add --global ksysgpowowidesll 'kubectl --namespace=kube-system get pods --watch -o=wide --show-labels -l'
    abbr --add --global kgdepwowidesll 'kubectl get deployment --watch -o=wide --show-labels -l'
    abbr --add --global ksysgdepwowidesll 'kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
    abbr --add --global kgwslowidel 'kubectl get --watch --show-labels -o=wide -l'
    abbr --add --global ksysgwslowidel 'kubectl --namespace=kube-system get --watch --show-labels -o=wide -l'
    abbr --add --global kgpowslowidel 'kubectl get pods --watch --show-labels -o=wide -l'
    abbr --add --global ksysgpowslowidel 'kubectl --namespace=kube-system get pods --watch --show-labels -o=wide -l'
    abbr --add --global kgdepwslowidel 'kubectl get deployment --watch --show-labels -o=wide -l'
    abbr --add --global ksysgdepwslowidel 'kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
    abbr --add --global kexn 'kubectl exec -i -t --namespace'
    abbr --add --global klon 'kubectl logs -f --namespace'
    abbr --add --global kpfn 'kubectl port-forward --namespace'
    abbr --add --global kgn 'kubectl get --namespace'
    abbr --add --global kdn 'kubectl describe --namespace'
    abbr --add --global krmn 'kubectl delete --namespace'
    abbr --add --global kgpon 'kubectl get pods --namespace'
    abbr --add --global kdpon 'kubectl describe pods --namespace'
    abbr --add --global krmpon 'kubectl delete pods --namespace'
    abbr --add --global kgdepn 'kubectl get deployment --namespace'
    abbr --add --global kddepn 'kubectl describe deployment --namespace'
    abbr --add --global krmdepn 'kubectl delete deployment --namespace'
    abbr --add --global kgsvcn 'kubectl get service --namespace'
    abbr --add --global kdsvcn 'kubectl describe service --namespace'
    abbr --add --global krmsvcn 'kubectl delete service --namespace'
    abbr --add --global kgingn 'kubectl get ingress --namespace'
    abbr --add --global kdingn 'kubectl describe ingress --namespace'
    abbr --add --global krmingn 'kubectl delete ingress --namespace'
    abbr --add --global kgcmn 'kubectl get configmap --namespace'
    abbr --add --global kdcmn 'kubectl describe configmap --namespace'
    abbr --add --global krmcmn 'kubectl delete configmap --namespace'
    abbr --add --global kgsecn 'kubectl get secret --namespace'
    abbr --add --global kdsecn 'kubectl describe secret --namespace'
    abbr --add --global krmsecn 'kubectl delete secret --namespace'
    abbr --add --global kgoyamln 'kubectl get -o=yaml --namespace'
    abbr --add --global kgpooyamln 'kubectl get pods -o=yaml --namespace'
    abbr --add --global kgdepoyamln 'kubectl get deployment -o=yaml --namespace'
    abbr --add --global kgsvcoyamln 'kubectl get service -o=yaml --namespace'
    abbr --add --global kgingoyamln 'kubectl get ingress -o=yaml --namespace'
    abbr --add --global kgcmoyamln 'kubectl get configmap -o=yaml --namespace'
    abbr --add --global kgsecoyamln 'kubectl get secret -o=yaml --namespace'
    abbr --add --global kgowiden 'kubectl get -o=wide --namespace'
    abbr --add --global kgpoowiden 'kubectl get pods -o=wide --namespace'
    abbr --add --global kgdepowiden 'kubectl get deployment -o=wide --namespace'
    abbr --add --global kgsvcowiden 'kubectl get service -o=wide --namespace'
    abbr --add --global kgingowiden 'kubectl get ingress -o=wide --namespace'
    abbr --add --global kgcmowiden 'kubectl get configmap -o=wide --namespace'
    abbr --add --global kgsecowiden 'kubectl get secret -o=wide --namespace'
    abbr --add --global kgojsonn 'kubectl get -o=json --namespace'
    abbr --add --global kgpoojsonn 'kubectl get pods -o=json --namespace'
    abbr --add --global kgdepojsonn 'kubectl get deployment -o=json --namespace'
    abbr --add --global kgsvcojsonn 'kubectl get service -o=json --namespace'
    abbr --add --global kgingojsonn 'kubectl get ingress -o=json --namespace'
    abbr --add --global kgcmojsonn 'kubectl get configmap -o=json --namespace'
    abbr --add --global kgsecojsonn 'kubectl get secret -o=json --namespace'
    abbr --add --global kgsln 'kubectl get --show-labels --namespace'
    abbr --add --global kgposln 'kubectl get pods --show-labels --namespace'
    abbr --add --global kgdepsln 'kubectl get deployment --show-labels --namespace'
    abbr --add --global kgwn 'kubectl get --watch --namespace'
    abbr --add --global kgpown 'kubectl get pods --watch --namespace'
    abbr --add --global kgdepwn 'kubectl get deployment --watch --namespace'
    abbr --add --global kgsvcwn 'kubectl get service --watch --namespace'
    abbr --add --global kgingwn 'kubectl get ingress --watch --namespace'
    abbr --add --global kgcmwn 'kubectl get configmap --watch --namespace'
    abbr --add --global kgsecwn 'kubectl get secret --watch --namespace'
    abbr --add --global kgwoyamln 'kubectl get --watch -o=yaml --namespace'
    abbr --add --global kgpowoyamln 'kubectl get pods --watch -o=yaml --namespace'
    abbr --add --global kgdepwoyamln 'kubectl get deployment --watch -o=yaml --namespace'
    abbr --add --global kgsvcwoyamln 'kubectl get service --watch -o=yaml --namespace'
    abbr --add --global kgingwoyamln 'kubectl get ingress --watch -o=yaml --namespace'
    abbr --add --global kgcmwoyamln 'kubectl get configmap --watch -o=yaml --namespace'
    abbr --add --global kgsecwoyamln 'kubectl get secret --watch -o=yaml --namespace'
    abbr --add --global kgowidesln 'kubectl get -o=wide --show-labels --namespace'
    abbr --add --global kgpoowidesln 'kubectl get pods -o=wide --show-labels --namespace'
    abbr --add --global kgdepowidesln 'kubectl get deployment -o=wide --show-labels --namespace'
    abbr --add --global kgslowiden 'kubectl get --show-labels -o=wide --namespace'
    abbr --add --global kgposlowiden 'kubectl get pods --show-labels -o=wide --namespace'
    abbr --add --global kgdepslowiden 'kubectl get deployment --show-labels -o=wide --namespace'
    abbr --add --global kgwowiden 'kubectl get --watch -o=wide --namespace'
    abbr --add --global kgpowowiden 'kubectl get pods --watch -o=wide --namespace'
    abbr --add --global kgdepwowiden 'kubectl get deployment --watch -o=wide --namespace'
    abbr --add --global kgsvcwowiden 'kubectl get service --watch -o=wide --namespace'
    abbr --add --global kgingwowiden 'kubectl get ingress --watch -o=wide --namespace'
    abbr --add --global kgcmwowiden 'kubectl get configmap --watch -o=wide --namespace'
    abbr --add --global kgsecwowiden 'kubectl get secret --watch -o=wide --namespace'
    abbr --add --global kgwojsonn 'kubectl get --watch -o=json --namespace'
    abbr --add --global kgpowojsonn 'kubectl get pods --watch -o=json --namespace'
    abbr --add --global kgdepwojsonn 'kubectl get deployment --watch -o=json --namespace'
    abbr --add --global kgsvcwojsonn 'kubectl get service --watch -o=json --namespace'
    abbr --add --global kgingwojsonn 'kubectl get ingress --watch -o=json --namespace'
    abbr --add --global kgcmwojsonn 'kubectl get configmap --watch -o=json --namespace'
    abbr --add --global kgsecwojsonn 'kubectl get secret --watch -o=json --namespace'
    abbr --add --global kgslwn 'kubectl get --show-labels --watch --namespace'
    abbr --add --global kgposlwn 'kubectl get pods --show-labels --watch --namespace'
    abbr --add --global kgdepslwn 'kubectl get deployment --show-labels --watch --namespace'
    abbr --add --global kgwsln 'kubectl get --watch --show-labels --namespace'
    abbr --add --global kgpowsln 'kubectl get pods --watch --show-labels --namespace'
    abbr --add --global kgdepwsln 'kubectl get deployment --watch --show-labels --namespace'
    abbr --add --global kgslwowiden 'kubectl get --show-labels --watch -o=wide --namespace'
    abbr --add --global kgposlwowiden 'kubectl get pods --show-labels --watch -o=wide --namespace'
    abbr --add --global kgdepslwowiden 'kubectl get deployment --show-labels --watch -o=wide --namespace'
    abbr --add --global kgwowidesln 'kubectl get --watch -o=wide --show-labels --namespace'
    abbr --add --global kgpowowidesln 'kubectl get pods --watch -o=wide --show-labels --namespace'
    abbr --add --global kgdepwowidesln 'kubectl get deployment --watch -o=wide --show-labels --namespace'
    abbr --add --global kgwslowiden 'kubectl get --watch --show-labels -o=wide --namespace'
    abbr --add --global kgpowslowiden 'kubectl get pods --watch --show-labels -o=wide --namespace'
    abbr --add --global kgdepwslowiden 'kubectl get deployment --watch --show-labels -o=wide --namespace'
end
