;; Mouse mode in terminal + scrolling on Mac OS
(unless (display-graphic-p)
  (require 'mouse)
  (xterm-mouse-mode t)
  (when (string-equal system-type "darwin")
    (global-set-key [mouse-4] (lambda () (interactive) (scroll-down 1)))
    (global-set-key [mouse-5] (lambda () (interactive) (scroll-up 1)))
    )
  (defun track-mouse (e))
  (setq mouse-sel-mode t)
  )
