FROM {{ image.base }}:{{ image.tag }}

ENV THEME_ENABLE_GLYPHS 1
{%- for k, v in image.env.items() %}
ENV {{ k }} {{ v }}
{%- endfor %}

{%- if image.run_commands %}
RUN {{ image.run_commands | join(' && \\\n\t') }}
{%- endif %}

RUN {{ image.package_manager }} {{ image.package_manager_argv | join(' ') }} {{ install_packages | join(' ') }}

WORKDIR /opt/dotfiles
COPY . .
RUN ./install.py {{ install_sh_argv | join(' ') }}

ENTRYPOINT ["{{ image.entrypoint }}"]
